### PR TITLE
adds opensearch support, closes #76

### LINKED ISSUE #76: Add support for opensearch
See:

``` xml
<link rel="search" type="application/opensearchdescription+xml" href="//d3df9uo7bhy7ev.cloudfront.net/assets/355274b/opensearch.xml" title="Artsy">
```

### PR DESCRIPTION
**Pull request by taveras**

### CODE REVIEW

**Comment by segiddins** [comment]
http://cocoapods.org/opensearch.xml 404s for me

**Comment by taveras** [comment]
Eek, try it now. Forgot to actually add the xml file :(

**Comment by orta** [comment]
This looks :star: 

Exploding planet

**Comment by orta** [comment]
It will require a manual deploy, so it won't be instantly on the site.

**Pull request merged**
