### PR TITLE
Bring back average quality on owners page

### PR DESCRIPTION
**Pull request by k0nserv**
With no pods
screen shot 2015-10-11 at 16 46 35

With pods
screen shot 2015-10-11 at 16 46 24

cc @orta

### CODE REVIEW

**Comment by k0nserv** [comment]
I feel like the alignment could be improved. Is there are reason why the tds on this page have a fixed height?

**Comment by floere** [comment]
@orta ^

**Comment by orta** [comment]
So this is what I choose to not ship. I'm not sure if it works well with the rest of the top menu, as @k0nserv is saying right now. I couldn't find a good design answer for it. 

The fixed height was likely to do with ensure it all works on mobile etc

**Comment by k0nserv** [comment]
Okay, my CSS skills are a bit dormant, but I'll have a look and see if I can't improve it without having the fixed height

**Pull request merged**
