### PR TITLE
[Code] Fix code formatting breaking lines

### PR DESCRIPTION
**Pull request by k0nserv**
I am not sure if this breaks some other part of the application. The previous commit was from you @orta, I'll add a specific override for about in that case

### CODE REVIEW

**Comment by k0nserv** [comment]
Relating to https://github.com/CocoaPods/cocoapods.org/issues/174

**Comment by segiddins** [comment]
Should overflow-X: scroll?

**Comment by orta** [comment]
I don't think we can win on this one, I think mine & k0nserv's options are pretty bad, but maybe @segiddins' is worth a try.

**Comment by k0nserv** [comment]
Is there are reason for preferring `overflow-x: scroll` Horizontal scrolling is pretty unwanted behaviour. I guess there's an issue of the section matching the height of the section to the right?

**Comment by segiddins** [comment]
I've always used horizontal scroll for code, since wrapping doesn't really work at all

**Comment by k0nserv** [comment]
I agree in general, but this is not for large blocks of multiline code, the issue is mainly about markdown backticks for small pieces of code like `pod install`

**Comment by orta** [comment]
I'm wary of this still, there are a lot of places where this breaks because of objective-c's nature to have surer long method/pod names. I'll have changed it to break on letter for a good reason.

**Comment by k0nserv** [comment]
How about just a local override for the about page?

**Comment by orta** [comment]
I'm totally cool with that :dancers:

**Comment by orta** [comment]
ping @k0nserv

**Comment by k0nserv** [comment]
Oops, I need a todo app of some kind I think :)

**Comment by orta** [comment]
Awesome!

**Pull request merged**
