### PR TITLE
Update sample podfile to latest version of AFN

### PR DESCRIPTION
**Pull request by kleinlieu**
Updating AFNetworking to 2.6.0. Also adds an example that shows you can point to a patch version in podfile.

### CODE REVIEW

**Comment by orta** [comment]
Thanks @kleinlieu - if you change this to only `2.6` we'll get this merged. We generally don't recommend using the `~>` operator with a patch, people get surprised when it updates cause they think it is a lock.

**Comment by orta** [comment]
sorry for taking a while!

**Comment by kleinlieu** [comment]
@orta ready for review again. I also updated the other pods in the documentation.

**Comment by orta** [comment]
ACE thanks!

**Pull request merged**
