### PR TITLE
[search] Unique the entries in our results

### PR DESCRIPTION
**Pull request by orta**
If #220 and #226 come from the search server, I'd rather be extra paranoid against it in the client.

### CODE REVIEW

**Comment by floere** [comment]
Does the code actually work? `jQuery.unique([{a: 1}, {a: 1}])` for example results in `[{a: 1}, {a: 1}]`.

**Comment by floere** [comment]
Other than that I like the idea – if the issue still occurs, we can continue searching for the issue in the client. Otherwise, in the search engine.

**Comment by floere** [comment]
This is probably not the way to go (from https://api.jquery.com/jQuery.unique/):

> A node is considered a duplicate if it is the exact same node as one already in the array; two different nodes with identical attributes are not considered to be duplicates. This function only works on plain JavaScript arrays of DOM elements, and is chiefly used internally by jQuery. You probably will never need to use it.

**Comment by orta** [comment]
Yeah, I read this too

**Comment by floere** [comment]
@orta Mind reverting this (or make it work) if you're currently working on the site? Cheers!

**Comment by orta** [comment]
it's in the 1.0 branch

**Comment by floere** [comment]
@orta Thanks! :)

**Pull request merged**
