### PR TITLE
Migrate a chunk of inactive contributors team to alumni <3 - 

### LINKED ISSUE #291: Bring Boris back as Alumni
#290 deleted him completely, but really we want him in the alumni

### PR DESCRIPTION
**Pull request by orta**
it is/was awesome working with you all

screen shot 2016-09-14 at 8 27 57 am

@DanToml / @benasher44 - happy to jam with you two on what your tagline is, I generally try to make them alliterate but I'm pretty chill on what this looks like

@benasher44 - would love for you to get yourself a twitter background, if you're not sure of what, I'd love to see a landscape from where you grew up, but you can totally do whatever you want 👍 

fixes #291

### CODE REVIEW

**Comment by segiddins** [comment]
💞

**Comment by benasher44** [comment]
@orta Thanks! I'll see what I can do! Yeah let me fix up my Twitter bio a bit, and I'll get back to ya.

**Comment by DanToml** [comment]
💖 - (LGTM)

**Comment by benasher44** [comment]
@orta I updated my Twitter profile photos: background and all! The tagline as you have it sounds good. I couldn't come up with any fresh ideas. ship it!

**Comment by alloy** [comment]
PS I should update my twitter background image, will do so today.

**Comment by alloy** [comment]
Done.

**Comment by orta** [comment]
Cool -shipping

**Pull request merged**
