### PR TITLE
[Routing] Only return 404 if a slim file did not exist

### PR DESCRIPTION
**Pull request by k0nserv**
/c @orta

### CODE REVIEW

**Comment by segiddins** [comment]
Why is this necessary?

**Comment by k0nserv** [comment]
Because it will return 404 regardless of any slim page being rendered effectively overriding the 200 status and output of the rendering

**Comment by orta** [comment]
the first bit doesn't return the `slim` ending, it would get to a 404 after and that would be the end result of the route

**Comment by orta** [comment]
deploying

**Comment by k0nserv** [comment]
Great :+1:

**Pull request merged**
