### PR TITLE
Mention brew cask installation method

### PR DESCRIPTION
**Pull request by neonichu**
Since people want to use homebrew and we support it via cask, let's also mention it on the website.

See discussion on CocoaPods/CocoaPods#2238

cc @orta

### CODE REVIEW

**Comment by hfossli** [comment]
Nice. Is it required that I open the app and hit Install the Command Line Tool" as well?
screen shot 2015-07-23 at 14 06 46

And should I then first `$ [sudo] gem uninstall cocoapods`?

**Comment by hfossli** [comment]
If necessary: Maybe the app should automatically open and prompt the user to install the CLI tools

**Comment by neonichu** [comment]
Nope, the cask takes care of that: https://github.com/caskroom/homebrew-cask/blob/master/Casks/cocoapods.rb#L17-L18

**Comment by alloy** [comment]
@neonichu :+1:

**Comment by alloy** [comment]
> If necessary: Maybe the app should automatically open and prompt the user to install the CLI tools

@hfossli Did you install via homebrew cask? If so, then [it doesn’t ask for it](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cocoapods.rb#L17-L18) because homebrew cask wants to do list own binstub symlinking.

If you install it outside of homebrew cask [it would](https://github.com/CocoaPods/CocoaPods-app/blob/master/app/CocoaPods/CPCLIToolInstallationController.m) automatically ask you on startup.

**Comment by alloy** [comment]
Hmm, actually the key being used in the cask formula is out-of-date https://github.com/CocoaPods/CocoaPods-app/blob/master/app/CocoaPods/CPCLIToolInstallationController.m#L7

**Comment by alloy** [comment]
Sent a PR https://github.com/caskroom/homebrew-cask/pull/12762

**Comment by alloy** [comment]
I seemed to have misunderstood this PR at first.

I feel like it’s hard to choose the cask or the normal homebrew way as being preferable over one another. So I think we should either have no homebrew mentioning at all or they should both be there. I’m still not sure yet, I don’t even really know why we support the cask one.

@neonichu’s idea for the latter case was that the LHS would mention the normal formula and the RHS would mention the cask. /cc @orta

**Comment by mikemcquaid** [comment]
> @neonichu’s idea for the latter case was that the LHS would mention the normal formula and the RHS would mention the cask. /cc @orta

Note that Homebrew by default will suggest the Cask if you on the failure of `brew install cocoapods` but not @keith's formula as it's not in an official Homebrew tap.

**Comment by alloy** [comment]
> Note that Homebrew by default will suggest the Cask if you on the failure of brew install cocoapods but not @keith's formula as it's not in an official Homebrew tap.

Oooh, that might actually be more reason for us to remove the cask, as I don’t think users that install through normal homebrew would expect or even want the app bundle approach.

Can we instead print a message on a build failure that suggests the existence of the app and provide a link to it?

**Comment by alloy** [comment]
Oh wait, you said “suggests”, so it does basically that what I suggested, except it goes through the cask, my bad.

Still, ca new have a custom message on build failure?

**Comment by mikemcquaid** [comment]
@alloy Sorry, I mean in even of a `brew install cocoapods` currently it'll do:

```
Error: No available formula for cocoapods 
==> Searching formulae...
==> Searching taps...
Caskroom/cask/cocoapods
```

So it's not that the formula has failed but that there is none available.

**Pull request closed without merging**
