### PR TITLE
Remove the references to the QIs in the authors page

### PR DESCRIPTION
**Pull request by orta**
Also fixes https://github.com/CocoaPods/cocoapods.org/issues/402 because now all pods are shown - not just ones we have rich metadata for

fixes https://github.com/CocoaPods/cocoapods.org/issues/392

### CODE REVIEW

**Comment by orta** [comment]
Also removes the GitHub and install stats, these haven't been useful in a year or two now.

**Comment by iDevelopper** [comment]
Does not work for me!

**Comment by orta** [comment]
I'm not sure what you mean? I removed the pages, which would mean that it should be working

**Comment by iDevelopper** [comment]
No description for PBPopupController:
screencapture-cocoapods-org-owners-14098-2019-03-31-19_31_09



And for PBRevealViewController:

**Pull request merged**
